// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureFitness.Context;

#nullable disable

namespace PureFitness.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251211051838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PureFitness.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Attendance_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<string>("Activity")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("Attendance_Date");

                    b.Property<string>("AttendanceStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Attendance_Status");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int")
                        .HasColumnName("Receipt_ID");

                    b.Property<TimeOnly?>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TimeOut")
                        .HasColumnType("time");

                    b.Property<int?>("TimeSpent")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__57FA4934CD4969B3");

                    b.HasIndex("MemberId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("PureFitness.Models.DietPlan", b =>
                {
                    b.Property<int>("DietPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DietPlan_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietPlanId"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.HasKey("DietPlanId")
                        .HasName("PK__DietPlan__92355CDC9ECA58FD");

                    b.HasIndex("MemberId");

                    b.HasIndex("StaffId");

                    b.ToTable("DietPlan", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.DietPlanItem", b =>
                {
                    b.Property<int>("DietPlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DietPlanItem_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietPlanItemId"));

                    b.Property<int>("CalorieTarget")
                        .HasColumnType("int");

                    b.Property<int?>("DietPlanId")
                        .HasColumnType("int")
                        .HasColumnName("DietPlan_ID");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DietPlanItemId")
                        .HasName("PK__DietPlan__DBEA1A9CE779835C");

                    b.HasIndex("DietPlanId");

                    b.ToTable("DietPlanItem", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("EquipmentCategory")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_Category");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_Name");

                    b.Property<string>("Program")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__C0F077C54A02FF36");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentItem", b =>
                {
                    b.Property<int>("EquipmentItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentItemId"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    b.Property<string>("EquipmentItemName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_ItemName");

                    b.Property<string>("EquipmentItemStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_ItemStatus");

                    b.HasKey("EquipmentItemId")
                        .HasName("PK__Equipmen__4428EEFA2448AA05");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentItem", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Log_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateOnly?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__Equipmen__2D26E7AED89A69D3");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Equipment_Logs", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    b.Property<int?>("EquipmentItemId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ItemID");

                    b.Property<string>("Frequency")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("MaintenanceDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NextMaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Equipmen__9C8A5B49BA06112B");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("EquipmentItemId");

                    b.HasIndex("StaffId");

                    b.ToTable("EquipmentSchedules");
                });

            modelBuilder.Entity("PureFitness.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Inventory_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    b.Property<int?>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Product_Quantity");

                    b.Property<string>("ProductStatus")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Product_Status");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__2B65F40B43D6D272");

                    b.HasIndex("ProductId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("AccessType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Access_Type");

                    b.Property<int?>("ActivityPoints")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("Bmi")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("BMI");

                    b.Property<DateOnly?>("CancellationDate")
                        .HasColumnType("date")
                        .HasColumnName("Cancellation_Date");

                    b.Property<DateOnly?>("DateJoined")
                        .HasColumnType("date")
                        .HasColumnName("Date_Joined");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("Due_Date");

                    b.Property<string>("FitnessGoal")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Fitness_Goal");

                    b.Property<string>("Fname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FName");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("Lname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LName");

                    b.Property<string>("MembershipPeriod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Membership_Period");

                    b.Property<string>("MembershipType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Membership_Type");

                    b.Property<string>("PaidStatus")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Paid_Status");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Phone_Number");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MemberId")
                        .HasName("PK__Members__42A68F2704A2A553");

                    b.HasIndex("StaffId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("PureFitness.Models.Payment", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Receipt_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<string>("AccessType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Change")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("InventoryId")
                        .HasColumnType("int")
                        .HasColumnName("Inventory_ID");

                    b.Property<int?>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Items")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Payment_Type");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Total_Cost");

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("Transaction_Date");

                    b.Property<string>("WalkInName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReceiptId")
                        .HasName("PK__Payments__38B787CCCBC02627");

                    b.HasIndex("InventoryId");

                    b.HasIndex("MemberId");

                    b.HasIndex("StaffId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PureFitness.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Product_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Product_Name");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("Product_Price");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__9834FBBACB251D5E");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PureFitness.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__D80AB49B36427027");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("AssignedTask")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Phone_Number");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("StaffId")
                        .HasName("PK__Staffs__32D1F3C35688645F");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("PureFitness.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Supplier_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__83918DB87377D50D");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__206D9190BAC38406");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PureFitness.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("WorkoutPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkoutPlan_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutPlanId"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.HasKey("WorkoutPlanId")
                        .HasName("PK__WorkoutP__D9FFB67298176932");

                    b.HasIndex("MemberId");

                    b.HasIndex("StaffId");

                    b.ToTable("WorkoutPlan", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.WorkoutPlanItem", b =>
                {
                    b.Property<int>("WorkoutPlanItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Workout_Plan_ItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkoutPlanItemId"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Exercise_Name");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int")
                        .HasColumnName("WorkoutPlan_ID");

                    b.HasKey("WorkoutPlanItemId")
                        .HasName("PK__WorkoutP__1B6AA810E2480470");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutPlanItem", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.Attendance", b =>
                {
                    b.HasOne("PureFitness.Models.Member", "Member")
                        .WithMany("Attendances")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__Attendanc__Membe__5BE2A6F2");

                    b.HasOne("PureFitness.Models.Payment", "Receipt")
                        .WithMany("Attendances")
                        .HasForeignKey("ReceiptId")
                        .HasConstraintName("FK__Attendanc__Recei__5CD6CB2B");

                    b.Navigation("Member");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("PureFitness.Models.DietPlan", b =>
                {
                    b.HasOne("PureFitness.Models.Member", "Member")
                        .WithMany("DietPlans")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__DietPlan__Member__68487DD7");

                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("DietPlans")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__DietPlan__Staff___693CA210");

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.DietPlanItem", b =>
                {
                    b.HasOne("PureFitness.Models.DietPlan", "DietPlan")
                        .WithMany("DietPlanItems")
                        .HasForeignKey("DietPlanId")
                        .HasConstraintName("FK__DietPlanI__DietP__6D0D32F4");

                    b.Navigation("DietPlan");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentItem", b =>
                {
                    b.HasOne("PureFitness.Models.Equipment", "Equipment")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__Equipment__Equip__44FF419A");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentLog", b =>
                {
                    b.HasOne("PureFitness.Models.EquipmentSchedule", "Schedule")
                        .WithMany("EquipmentLogs")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK__Equipment__Sched__4CA06362");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentSchedule", b =>
                {
                    b.HasOne("PureFitness.Models.Equipment", "Equipment")
                        .WithMany("EquipmentSchedules")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__Equipment__Equip__47DBAE45");

                    b.HasOne("PureFitness.Models.EquipmentItem", "EquipmentItem")
                        .WithMany("EquipmentSchedules")
                        .HasForeignKey("EquipmentItemId")
                        .HasConstraintName("FK__Equipment__Equip__48CFD27E");

                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("EquipmentSchedules")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Equipment__Staff__49C3F6B7");

                    b.Navigation("Equipment");

                    b.Navigation("EquipmentItem");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.Inventory", b =>
                {
                    b.HasOne("PureFitness.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK__Inventory__Produ__5441852A");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PureFitness.Models.Member", b =>
                {
                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("Members")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Members__Staff_I__403A8C7D");

                    b.HasOne("PureFitness.Models.User", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Members__User_ID__3F466844");

                    b.Navigation("Staff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFitness.Models.Payment", b =>
                {
                    b.HasOne("PureFitness.Models.Inventory", "Inventory")
                        .WithMany("Payments")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("FK__Payments__Invent__59063A47");

                    b.HasOne("PureFitness.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__Payments__Member__5812160E");

                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("Payments")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Payments__Staff___571DF1D5");

                    b.Navigation("Inventory");

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.Product", b =>
                {
                    b.HasOne("PureFitness.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK__Products__Suppli__5165187F");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.HasOne("PureFitness.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Staffs__User_ID__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.HasOne("PureFitness.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__Role_ID__398D8EEE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PureFitness.Models.WorkoutPlan", b =>
                {
                    b.HasOne("PureFitness.Models.Member", "Member")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("MemberId")
                        .HasConstraintName("FK__WorkoutPl__Membe__5FB337D6");

                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__WorkoutPl__Staff__60A75C0F");

                    b.Navigation("Member");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.WorkoutPlanItem", b =>
                {
                    b.HasOne("PureFitness.Models.Equipment", "Equipment")
                        .WithMany("WorkoutPlanItems")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__WorkoutPl__Equip__656C112C");

                    b.HasOne("PureFitness.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("WorkoutPlanItems")
                        .HasForeignKey("WorkoutPlanId")
                        .HasConstraintName("FK__WorkoutPl__Worko__6477ECF3");

                    b.Navigation("Equipment");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("PureFitness.Models.DietPlan", b =>
                {
                    b.Navigation("DietPlanItems");
                });

            modelBuilder.Entity("PureFitness.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentItems");

                    b.Navigation("EquipmentSchedules");

                    b.Navigation("WorkoutPlanItems");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentItem", b =>
                {
                    b.Navigation("EquipmentSchedules");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentSchedule", b =>
                {
                    b.Navigation("EquipmentLogs");
                });

            modelBuilder.Entity("PureFitness.Models.Inventory", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PureFitness.Models.Member", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("DietPlans");

                    b.Navigation("Payments");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("PureFitness.Models.Payment", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("PureFitness.Models.Product", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("PureFitness.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.Navigation("DietPlans");

                    b.Navigation("EquipmentSchedules");

                    b.Navigation("Members");

                    b.Navigation("Payments");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("PureFitness.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.WorkoutPlan", b =>
                {
                    b.Navigation("WorkoutPlanItems");
                });
#pragma warning restore 612, 618
        }
    }
}
