// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureFitness.Context;

#nullable disable

namespace PureFitness.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250803161450_UpdateEquipmentTable")]
    partial class UpdateEquipmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PureFitness.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("EquipmentCategory")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_Category");

                    b.Property<string>("EquipmentName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Equipment_Name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__C0F077C5F63CB3A4");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Log_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("Equipment_ID");

                    b.Property<DateTime?>("MaintenanceDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Maintenance_Date");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    b.HasKey("LogId")
                        .HasName("PK__Equipmen__2D26E7AE92AE95D2");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("Equipment_Logs", (string)null);
                });

            modelBuilder.Entity("PureFitness.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Member_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("float")
                        .HasColumnName("BMI");

                    b.Property<DateTime?>("DateJoined")
                        .HasColumnType("datetime")
                        .HasColumnName("Date_Joined");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Due_Date");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Fname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FName");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Lname")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LName");

                    b.Property<string>("MembershipPeriod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Membership_Period");

                    b.Property<string>("MembershipType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Membership_Type");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WorkoutGoal")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Workout_Goal");

                    b.HasKey("MemberId")
                        .HasName("PK__Members__42A68F27A9A69564");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("PureFitness.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Role_name");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__D80AB49BE13F6BE8");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Staff_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Phone_Number");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("StaffId")
                        .HasName("PK__Staffs__32D1F3C3C815F184");

                    b.HasIndex("UserId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("Role_ID");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__206D91908856633C");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PureFitness.Models.EquipmentLog", b =>
                {
                    b.HasOne("PureFitness.Models.Equipment", "Equipment")
                        .WithMany("EquipmentLogs")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__Equipment__Equip__440B1D61");

                    b.HasOne("PureFitness.Models.Staff", "Staff")
                        .WithMany("EquipmentLogs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Equipment__Staff__44FF419A");

                    b.Navigation("Equipment");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PureFitness.Models.Member", b =>
                {
                    b.HasOne("PureFitness.Models.User", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Members__User_ID__3F466844");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.HasOne("PureFitness.Models.User", "User")
                        .WithMany("Staff")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Staffs__User_ID__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.HasOne("PureFitness.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__Role_ID__398D8EEE");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PureFitness.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentLogs");
                });

            modelBuilder.Entity("PureFitness.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PureFitness.Models.Staff", b =>
                {
                    b.Navigation("EquipmentLogs");
                });

            modelBuilder.Entity("PureFitness.Models.User", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Staff");
                });
#pragma warning restore 612, 618
        }
    }
}
